### ISSUE TITLE
大佬，com.ignoreos.jvmqq.sdk这个包在哪

### ISSUE THREAD

**Issue by usetool** [waynamigo/JVM_TIM#1]
下载了你的代码后，放在idea中运行，发现项目依赖的com.ignoreos.jvmqq.sdk这个包下的类都是不存在的，应该是一个jar包，求jar包

**Comment by EdaB832** [comment]
...刚看到，这个要自己打一下，依赖都在build里面（而且tx九月中旬的时候把协议更新了，考研一直没注意有人提issue，抱歉已经不能用了orz，刚准备关掉这个仓库
